name: Schedule Job for slack noti

on:
  schedule:
    # - cron: '30 02 * * 6' # In UTC: 5:30 PM every Friday
    # - cron: '40 20 * * 1' # In UTC: 11:40 AM every Monday
    - cron: '*/10 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install
      - name: Run scheduled job
        run: |
          npx ts-node slack-noti-for-study
        env:
          SLACK_HEUG_TEST: ${{ secrets.SLACK_HEUG_TEST }}
          BOOK_RECORD_DB_ID: ${{ secrets.BOOK_RECORD_DB_ID }}
          NOTION_BOOKS_RECORD: ${{ secrets.NOTION_BOOKS_RECORD }}
