name: 'test-slack-action'
on: workflow_dispatch

jobs:
  'slack-message':
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "key": "value",
              "foo": "bar"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
