name: 'test-slack-action'
on:
  pull_request_target:
    types: [opened, labeled]
jobs:
  'slack-message':
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert when hot fix PR came up
        uses: slackapi/slack-github-action@v1.23.0
        # if: |
        #   contains(github.event.pull_request.labels.*.name,'type: bug (hotfix)')
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "LABELS ${{ contains(github.event.pull_request.pull_request.labels.*.name, "bug") }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
