name: wow
env:
  WORKFLOW_LEVEL_SERVICE_VERSION_REF_NAME: ${{ github.ref_name }}
  WORKFLOW_LEVEL_SERVICE_VERSION: ${{ github.ref }}
  SERVICE_VERSION_2: $(echo ${{ github.ref }} | cut -d- -f2)"
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test:
    env:
      JOB_LEVEL_SERVICE_VERSION: ${{ github.ref }}JOB
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set version name to environmgitent variable'
        run: |
          echo "SERVICE_VERSION=${{ github.ref }}" >> $GITHUB_ENV 
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Run tests
        env:
          STEP_LEVEL_SERVICE_VERSION: ${{ github.ref }}STEP
        run: node scripts/test.js
      - name: Next step
        run: echo "This is the next step"
      - name: Check out
        run: |
          echo $SERVICE_VERSION
          echo $action_state
  new-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: CHECK THIS OUT
        env:
          SERVICE_VERION: ${{ (startsWith(github.ref, 'refs/tags/app-v') && github.ref_name) }}
        run: |
          SERVICE_VERSION=$(echo $SERVICE_VERION | sed 's/app-//')
          echo $SERVICE_VERSION
          SERVICE_VERSION=$(echo app-v1.3.3 | sed 's/app-//')
          echo $SERVICE_VERSION
