name: wow

on:
  push:
    branches:
      - fix/trigger-another-branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Run tests
        run: node scripts/test.js
      - name: Next step
        run: echo "This is the next step"
