name: wow
env:
  WORKFLOW_LEVEL_SERVICE_VERSION: ${{ github.ref }}WORKFLOW

on:
  push:
    branches:
      - fix/trigger-another-branch

jobs:
  test:
    env:
      JOB_LEVEL_SERVICE_VERSION: ${{ github.ref }}JOB
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      # - name: Set version name to environment variable'
      #   if: startsWith(github.ref, 'refs/tags/app-v')
      #   run: |
      #     echo "SERVICE_VERSION=$(echo ${{ github.ref }} | cut -d- -f2)" >> $GITHUB_ENV
      - name: Run tests
        env:
          STEP_LEVEL_SERVICE_VERSION: ${{ github.ref }}STEP
        run: node scripts/test.js
      - name: Next step
        run: echo "This is the next step"

  next-job:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Run tests
        run: node scripts/test.js
