name: 'test-slack-action'
on:
  pull_request_target:
    types: [opened, labeled]
jobs:
  'slack-message':
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert when hot fix PR came up
        uses: slackapi/slack-github-action@v1.23.0
        if: |
          contains(github.event.pull_request.labels.*.name, 'type: bug (hotfix)')
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "상황발생상황발생",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "야 hotfix 올라왓다 다들 긴장하고 빠른 배포가자 @frontend"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
