name: wow

on:
  push:
    branches:
      - fix/trigger-another-branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Hello World"
